### ISSUE TITLE
Provide pluggable exception handling strategy

### ISSUE THREAD

**Issue by whiter4bbit** [zalando-incubator/fahrschein#143]
When a listener fails with an exception `CursorManager.onError` called, exception escapes - as an outcome processing stops:
```java
    private void processBatch(Batch<T> batch) throws IOException {
        final Cursor cursor = batch.getCursor();
        try {
            listener.accept(batch.getEvents());
            cursorManager.onSuccess(eventName, cursor);
        } catch (EventAlreadyProcessedException e) {
            LOG.info("Events for [{}] partition [{}] at offset [{}] were already processed", eventName, cursor.getPartition(), cursor.getOffset());
        } catch (Throwable throwable) {
            cursorManager.onError(eventName, cursor, throwable);
            throw throwable;
        }
    }
```

In some cases it is useful to continue reading events and commit the cursor or read failed batch again. This can be up to user. What about providing pluggable strategy to handle batch processing exceptions, like this:

```java
    private void processBatch(Batch<T> batch) throws IOException {
        final Cursor cursor = batch.getCursor();
        try {
            listener.accept(batch.getEvents());
            cursorManager.onSuccess(eventName, cursor);
        } catch (EventAlreadyProcessedException e) {
            LOG.info("Events for [{}] partition [{}] at offset [{}] were already processed", eventName, cursor.getPartition(), cursor.getOffset());
        } catch (Throwable throwable) {
            exceptionHandlingStrategy.onException(throwable, cursor, cursorManager);
        }
    }
```

This can be done without breaking current API.

**Comment by jhorstmann** [comment]
The exception handling strategy currently is

 - `EventAlreadyProcessedException` ignore without committing
 - `IOExceptions` close connection and reconnect
 - `RuntimeException` abort streaming, has to be handled outside

What other strategies could be useful, and could they be implemented in the `Listener` itself?

**Comment by whiter4bbit** [comment]
I overlooked `EventAlreadyProcessedException` this behaviour is exactly what I need.
