### ISSUE TITLE
Support subscription with initial cursors

### ISSUE THREAD

**Issue by jhorstmann** [zalando-incubator/fahrschein#147]
See nakadi release notes for 2017W09 and https://github.com/zalando/nakadi/blob/6b2e65b21dd46b414601f2ef14ebf832cd8b3d5d/api/nakadi-event-bus-api.yaml#L1785

**Comment by AdnanKukuljac** [comment]
@jhorstmann Maybe you can close this one?

**Comment by jhorstmann** [comment]
Fixed by #150
