### ISSUE TITLE
Simplify building of ClientHttpRequestFactory and NakadiClient itself

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#15]
Clients have to provide a `requestFactory` to the `NakadiClient`, which can handle authorization and `problem`-responses.

``` java
final SimpleClientHttpRequestFactory requestFactoryDelegate = new SimpleClientHttpRequestFactory();
final ProblemHandlingClientHttpRequestFactory problemHandlingRequestFactory = new ProblemHandlingClientHttpRequestFactory(requestFactoryDelegate, objectMapper);
final ClientHttpRequestFactory requestFactory = new AuthorizedClientHttpRequestFactory(problemHandlingRequestFactory, () -> "MY_ACCESS_TOKEN");
```

As both is [mandatory](https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml) when communicating with _nakadi_ it would be great if _fahrschein_ could offer an easy way to wrap a client's `requestFactory`.

**Comment by jhorstmann** [comment]
I introduced this in the latest commit of PR #18 

https://github.com/zalando-incubator/fahrschein/blob/close-http-components/src/main/java/org/zalando/fahrschein/ClientHttpRequestFactoryHelper.java

I don't like the name though, especially as we discussed having no "helpers" or "utils" so far :)

**Comment by lukasniemeier-zalando** [comment]
We could hide this in a `NakadiClientBuilder` like this:

```java
client = NakadiClient.Builder.for("https://my.nakadi.zalan.do")
    .withBackoff(new ExponentialBackoff())
    .withCursorManager(new PersistentCursorManager())
    .wrappingRequestFactory(new HttpComponentsRequestFactory())
    .build();
```

`ExponentialBackoff`, `inMemoryCursorManager` and `SimpleRequestFactory` can be defaults.

**Comment by jhorstmann** [comment]
One complication is that the `ManagedCursorManager` itself needs a `ClientHttpRequestFactory`, so once you use that you again have to configure everything yourself.

**Comment by tmuehl** [comment]
Why not creating the HttpClient inside `NakadiClient` instead of asking the user for it? We can let the user specify the Parameters (e.g. connection and read timeouts), which then could be also coordinated with the Nakadi parameters `stream_timeout`, `batch_flush_timeout` etc.
