### ISSUE TITLE
Add "unsubscribe" functionality to remove subscriptions from Nakadi

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando-incubator/fahrschein#164]
With the current version of "fahrschein" library it is possibly to create a subscription. Would be nice to have an "unsubscribe" method to programmatically manage subscriptions. It also enhances a bit a symmetry of a programming interface of this library.

Example use case: having this feature one can remove active subscriptions on shutdown of an application.

**Comment by jhorstmann** [comment]
Fixed by #165
