### ISSUE TITLE
Support wrapping on ManagedCursorManager

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#169]
Currently the `NakadiClientBuilder` automagically wraps the `RequestFactory`, providing support for `problem` and adding authorization as defined by the `AccessTokenProvider`.

In case client wants to provide her own `CursorManager`, she has to implement this wrapping on their own as it seems, as the classes are not public.

**Comment by jhorstmann** [comment]
Problem handling and authorization wrappers are also no longer public, would it be enough to do the wrapping inside the `ManagedCursorManager` constructor?

**Comment by lukasniemeier-zalando** [comment]
Auto-Wrapping inside the constructor is fine IMO, because it is consistent with the auto-wrapping done for the `NakadiClient`.
