### ISSUE TITLE
Slow Reconnect with HttpComponents

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#17]
If a client uses a `HttpComponentsClientHttpRequestFactory` re-connecting on processing failures (i.e.  `IOException`) is very slow. 

_fahrschein_ [tries to close](https://github.com/zalando-incubator/fahrschein/blob/master/src/main/java/org/zalando/fahrschein/NakadiReader.java#L190) the `ClientHttpResponse` in case of a failure. A `HttpComponentsClientHttpResponse` will always try to release the connection back to the connection manager [by consuming the full response body](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpResponse.java#L89) until an _EOF_. This can take an unpredictable amount of time, effectively pausing _fahrschein_.

See [here](https://github.com/lukasniemeier-zalando/fahrschein/blob/apache-blocks-on-close/src/test/java/org/zalando/fahrschein/NakadiReaderIT.java) for an example failing test.

**Comment by jhorstmann** [comment]
At first this looked like an issue in springs `HttpComponentsClientHttpResponse`, but I think this behaviour is built directly into apache httpclient. `EntityUtils` also just closes the input stream:

https://github.com/apache/httpcore/blob/4.4.x/httpcore/src/main/java/org/apache/http/util/EntityUtils.java#L88

The input stream implementation is probably `ChunkedInputStream`, which does the consumption:

https://github.com/apache/httpcore/blob/4.0.x/httpcore/src/main/java/org/apache/http/impl/io/ChunkedInputStream.java#L261

I actually assumed the `JsonParser` to already close the input stream, but it seems I was wrong and it considers the input stream to be managed outside.

**Comment by lukasniemeier-zalando** [comment]
`HttpComponentsClientHttpResponse` does explicitly use the `EntityUtils#consume` before unconditionally releasing the condition via `CloseableHttpResponse#close`.

```java
	@Override
	public void close() {
        // Release underlying connection back to the connection manager
        try {
            try {
                // Attempt to keep connection alive by consuming its remaining content
                EntityUtils.consume(this.httpResponse.getEntity());
            }
			finally {
                this.httpResponse.close();
            }
        }
        catch (IOException ex) {
			// Ignore exception on close...
        }
}
```

The stream managed by the `HttpComponentsClientHttpResponse` is a `EofSensorInputStream -> ChunkedInputStream` chain, correct, see [here](http://grepcode.com/file/repo1.maven.org/maven2/com.ning/metrics.action/0.2.0/org/apache/http/conn/EofSensorInputStream.java#237).

I see no way of skipping the behavior of `EntityUtils.consume(this.httpResponse.getEntity());` in `HttpComponentsClientHttpResponse`.

**Comment by jhorstmann** [comment]
I added a standalone integration test using embedded jetty in PR #18 and will now try some reflection hackery.

**Comment by jhorstmann** [comment]
Great, this exposed some more issues with the reconnection logic. Currently the `maxRetries` parameter was only checked for exceptions during the reconnection. That parameter should probably also apply to exceptions during processing.

**Comment by jhorstmann** [comment]
Ugly reflection-based workaround: https://github.com/zalando-incubator/fahrschein/blob/close-http-components/src/test/java/org/zalando/fahrschein/CloseableHttpComponentsClientRequestFactory.java#L64

**Comment by lukasniemeier-zalando** [comment]
We are running *fahrschein* with the adapted `requestFactory` from #19 successfully now.

**Comment by jhorstmann** [comment]
Reopening since we will now have the same issue with the simple implementation in issue #83

**Comment by lukasniemeier-zalando** [comment]
It seems like it is possible to consume the whole connection pool in case fahrschein is not able to (re-)connect.

```
[422]: [Unprocessable Entity] [Session with stream id 86f6f61c-773a-gh71-addd-086d6d28cfff not found]
...
Connection Pool Timeout...
```

I guess this might be related to the request not being freed properly?
