### ISSUE TITLE
How to Stop listening for events.

### ISSUE THREAD

**Issue by thomasabraham** [zalando-incubator/fahrschein#173]
I'm listening for events in one dedicated thread, while the main application performs other stuff.
The main application can start listening when it need by starting the thread. 
To stop listening, as of now the only way is to kill the thread. 
It will be nice if we can have a proper way to stop listening.

**Comment by jhorstmann** [comment]
See previous discussion in #161 and #163 

Can you explain in more detail how your usecase can not be solved by interrupting the thread?

**Comment by thomasabraham** [comment]
After going through [readme](https://github.com/zalando-incubator/fahrschein#stopping-and-resuming-streams) I understand my mistake. 

I used it with blocking listen, thats what go me stuck.
