### ISSUE TITLE
Support posting events to nakadi

### ISSUE THREAD

**Issue by jhorstmann** [zalando-incubator/fahrschein#48]
Or should this library concentrate only on the consuming part?

**Comment by lukasniemeier-zalando** [comment]
Producing events to nakadi is a (relative) simple _HTTP POST_, which can be done with cool libraries like [riptide](https://github.com/zalando/riptide). Or is there any complexity for the users involved I miss?

**Comment by jhorstmann** [comment]
The only complexity is that there could be partial failures with a [`BatchItemResponse`](https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L1087) result. We could implement automatic retries for some of the results, but maybe these more complicated use cases are better handled by [Tarbela](https://github.com/zalando-incubator/tarbela).

**Comment by danielrohe** [comment]
There could not only be partial failure with BatchItemResponse, we often also have certain timeouts and need to retry events or even not publish further events as long as a previous event is not published to ensure ordering.

**Comment by jhorstmann** [comment]
@danielrohe Retrying would be possible to handle in a library, but more complex use-cases are probably too application specific. I also want to avoid adding another persistence for events, so events to retry would only be stored in-memory.
