### ISSUE TITLE
Unable to connect to expired/empty topics

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#51]
It looks like `0.4.1` introduced a regression concerning expired and empty topics (low-level API).

### Scenario

On...
```
http GET https://nakadi.com/event-types/my-empty-topic/partitions
[
    {
        "newest_available_offset": "BEGIN",
        "oldest_available_offset": "0",
        "partition": "0"
    }
]
```
... with...
```java
cursorManager.updatePartitions(eventName, client.getPartitions(eventName));
client.listen(...);
```
... leads to...
        
    org.zalando.fahrschein.IOProblem: Problem [http://httpstatus.es/412] with status [412]: [Precondition Failed] [partition 0 is empty]

Similar for an expired topic...
```
[
    {
        "newest_available_offset": "1",
        "oldest_available_offset": "2",
        "partition": "0"
    }
]
```
... we get...

    org.zalando.fahrschein.IOProblem: Problem [http://httpstatus.es/412] with status [412]: [Precondition Failed] [offset 2 for partition 0 is unavailable]

### But Why

Might be in ``CursorManager#updatePartitions`` - it is always using the `oldest_available_offset` if no Cursor is available from the manager. Therefore maybe something like this:

    onSuccess(eventName, new Cursor(partition.getPartition(), fallbackToBegin ? "BEGIN" :  partition.getNewestOffset()));

With `fallbackToBegin` being added to the API.

**Comment by jhorstmann** [comment]
Is the `CursorManager` in this case a freshly created `InMemoryCursorManager` or did it have previous offset values persisted?

**Comment by lukasniemeier-zalando** [comment]
It's the JDBC one but with an empty database :wink:
