### ISSUE TITLE
Misleading log message after reconnect

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#52]
On _fahrschein_ `0.4.0` the following logs can be observed:

```
{WARN} [nakadi-1] [] [org.zalando.fahrschein.ExponentialBackoffStrategy] Got [NoConnectivityOnTheTrainException] on retry [5]
{INFO} [nakadi-1] [] [org.zalando.fahrschein.ExponentialBackoffStrategy] Retry [6], sleeping for [5695] milliseconds
{INFO} [nakadi-2] [] [org.zalando.fahrschein.NakadiReader] Reconnected after [0] errors
```

I'd expect `Reconnected after [5] errors` as the last log line.

**Comment by jhorstmann** [comment]
> I'd expect Reconnected after [5] errors as the last log line.

Me too: https://github.com/zalando-incubator/fahrschein/blob/master/src/main/java/org/zalando/fahrschein/NakadiReader.java#L276

What is the next log output from `nakadi-1` thread instead?

**Comment by lukasniemeier-zalando** [comment]
Oh I see. Let me check 😂
