### ISSUE TITLE
Why wrapping exception?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-incubator/fahrschein#58]
Callable.call throws Exception, why the wrapping here?

```java
    default Callable<T> unchecked() {
        return () -> {
            try {
                return call();
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        };
    }
```

**Comment by jhorstmann** [comment]
You are right, but I think the method is not used at the moment. I probably copied that from `IORunnable`, the idea there was that the `NakadiReader` could maybe become an implementation detail or that the `listen` methods could return a runnable that the client could then either execute directly or put into a thread pool.
