### ISSUE TITLE
Support planned metadata on first and last event batch

### ISSUE THREAD

**Issue by jhorstmann** [zalando-incubator/fahrschein#77]
See https://github.com/zalando/nakadi/pull/406

Unknown properties in the batch should be ignored, or at least the proposed `metadata` property needs to be recognized.

**Comment by rcillo** [comment]
Unknown properties everywhere should be ignored http://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-prepare-clients-for-compatible-api-extensions-the-robustness-principle

Be aware of the field definitionhttps://github.com/zalando/nakadi/blob/bedfda6279e118fd91514ec7e08ded301c30e5d0/api/nakadi-event-bus-api.yaml#L1165-L1170

> This object contains general information about the stream. Used only for debugging
      purposes. We recommend logging this object in order to solve connection issues. Clients
      should not parse this structure.
