### ISSUE TITLE
Release First Version

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#8]
*As* a early adopter
*I want* to have an early release candidate released
*So that* I can use this library in production secretly.

**Comment by lukasniemeier-zalando** [comment]
This may be blocked by #5 or fixes #5 - you decide :wink:

**Comment by jhorstmann** [comment]
Released 0.1.0 from master. Issue #5 will be fixed together with #7 which is planned for 0.2.0
