### ISSUE TITLE
Closing SimpleHttpClientResponse tries to drain response in spring 4.3.x

### ISSUE THREAD

**Issue by jhorstmann** [zalando-incubator/fahrschein#83]
Fahrschein tries to close the `ClientHttpResponse` in case of any exception in order to retry consuming the stream from a clean state. With current spring versions, this blocks trying to consume remaining data, until the nakadi server decides to close the connection.

Related to issue #17 for `HttpComponentsClientHttpResponse`, the same behaviour was added to `SimpleHttpClientResponse` in https://github.com/spring-projects/spring-framework/commit/b947bfe8e99271b4d88a5a5aba0a8960f76b8efd

**Comment by jhorstmann** [comment]
Related discussion in https://jira.spring.io/browse/SPR-14040 and https://jira.spring.io/browse/SPR-14882

**Comment by lukasniemeier-zalando** [comment]
Any update on this? :wink:

**Comment by jhorstmann** [comment]
Yes, watch this space: https://github.com/zalando-incubator/fahrschein-http

Unfortunately dropping the required spring dependency also means rewriting all tests relying on `MockRestServiceServer`.

**Comment by jhorstmann** [comment]
Fixed in [release 0.10.0](https://github.com/zalando-incubator/fahrschein/releases/tag/0.10.0) by including our own implementation
