### ISSUE TITLE
Add generic `data` property to `DataChangeEvent` interface

### ISSUE THREAD

**Issue by jhorstmann** [zalando-incubator/fahrschein#91]
As a reminder for users that data change events are nested differently.

**Comment by danielrohe** [comment]
Also keep in mind that Jackson2 needs type information for the parametrized type to deserialize it correctly, something like:

    JavaType myDataChangeEvent = objectMapper().getTypeFactory().constructParametricType(DataChangeEvent.class, MyResource.class);
    MyResource eventData = objectMapper.readValue(jsonString, myDataChangeEvent);

otherwise afaik it will create a Map with key-value pairs for the attributes.

**Comment by jhorstmann** [comment]
I think this should just work if you have a concrete subclass of `DataChangeEvent`:

    class MyEntity { }
    class MyEvent implements DataChangeEvent<MyEntity> { }

**Comment by jhorstmann** [comment]
Fixed by #101
